### ISSUE TITLE
Turn decrypt into a total function (make it isomorphic to decryptEither)

### ISSUE THREAD

**Issue by adinapoli** [RNCryptor/rncryptor-hs#20]
This stems from comments from this onwards: https://github.com/RNCryptor/rncryptor-hs/issues/18#issuecomment-264391161

`decrypt` is affected by the very same "malady" of some Haskell non-total functions (e.g. `head`). It can fail and explode on user's face in case something went wrong. Although this could be in some cases a perfectly acceptable behaviour (a sort of panic button to signal a bug in the code) I think the other side of the coin is pretty strong as well: as Haskellers we should escape from non-total functions, and use appropriate types for error handling when possible.

I think for this reason it makes sense to do the following:

* Before `1.0.0` lands, we add a deprecation warning to `decrypt`, (via the `DEPRECATED` pragma) asking the user to use `decryptEither` as the type of decrypt will change to be a total function in `1.0.0`

* When `1.0.0` lands, we basically alias `decrypt` to `decryptEither`.

The only snag of this plan is that now we have two functions exposed in the API, namely `decrypt` and `decryptEither` which does exactly the same. To obviate this, we could make `decryptEither` private in `1.1.0`, but that could piss the user off as it would need to switch once again from `decryptEither` to `decrypt` (although the types are the same and the refactoring would involve only renaming a function). We could of course mitigate this with deprecation pragmas.

@timbod7 @rnapier @tomtitchener What do you guys think? Overkill? Bikeshedding?

**Comment by tomtitchener** [comment]
@timbod7 @rnapier @adinapoli 

What I think is it's great to have clients!  And contributors!  I don't know how many there are in total.  Based on contributions and discussions in the repo, I don't think there can be that many.

The fewer the clients, the stronger weight each point of view carries.

I'm happy to change my code the following your path when we get to 1.0.0.

There's not that much to it!

**Comment by timbod7** [comment]
@adinapoli - this feels overly conservative to me. If you ultimately only want to have

```
decrypt :: ByteString -> ByteString -> Either RNCryptorException ByteString
```

I'd just make this change, and push a new version to hackage with a version bump indicating the API has changed (0.1). I think this is reasonable, as it won't break anything code against the current version (assuming that code has correct version bounds), and it's a simple enough change to upgrade when required.

There's appears to only be [one defunct package][1] on hackage that depends on this code in any case.

[1]: http://packdeps.haskellers.com/reverse/rncryptor

**Comment by adinapoli** [comment]
Hey folks!

(Sorry for the brief tone,  I'm  on  mobile).

Right, I think  you  guys  are damn  right, we  shouldn't be too concerned
about breaking  things at this  stage,  as it's more important to attract
 contributors and  users of the  library.

Right  then, will seize the chance of  finalizing the next release which
 incorporates Tim's changes as the perfect excuse to also do this small
change.  thanks for the  insights folks!
