### ISSUE TITLE
Relax the upper bound on QuickCheck package

### ISSUE THREAD

**Issue by Mikolaj** [RNCryptor/rncryptor-hs#28]
It conflicts with bounds of some packages compiled with GHC 8.4.4.

**Comment by Mikolaj** [comment]
@adinapoli: could you release this on Hackage? It compiles fine for me on GHC 8.4.4. Thank you!

**Comment by adinapoli** [comment]
@Mikolaj Released on Hackage!

**Comment by Mikolaj** [comment]
Thank you very much, Alfredo!
